### ISSUE TITLE
[MC VERSION] UltimateTimber и ошибки

### ISSUE THREAD

**Issue by XionioXMaster** [MinecraftMist/Mist#19]
Minecraft Version : 1.16.5
Mist Version : 13
Operating System : Унтбунту 20
Concerned mod / plugin : https://haste.mohistmc.com/gaqihepoxu

**Logs :** `>....at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:876) ~[?:?]
[06:23:20 ERROR]: Could not pass event BlockBreakEvent to UltimateTimber v2.2.5
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[forge:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
at com.mohistmc.eventhandler.dispatcher.BlockEventDispatcher.onBreakBlockEvent(BlockEventDispatcher.java:22) ~[forge:?]
at net.minecraftforge.eventbus.ASMEventHandler_220_BlockEventDispatcher_onBreakBlockEvent_BreakEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:609) ~[forge:?]
at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:296) ~[?:?]
at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:285) ~[?:?]
at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:255) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:1429) ~[?:?]
at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:882) ~[?:?]
at com.songoda.ultimatetimber.manager.TreeFallManager.onBlockBreak(TreeFallManager.java:146) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:135) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:862) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:782) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283) ~[?:?]
at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
at com.songoda.ultimatetimber.core.world.SItemStack.addDamage(SItemStack.java:44) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor191.invoke(Unknown Source) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
... 30 more`

**Steps to Reproduce :**
 1. Срубить дерево что бы проигралась анимация, посмотреть в лог

**Comment by KR33PY** [comment]
Не воспроизводится на Mist 14 + Ultimate Timber 2.2.5
