### ISSUE TITLE
[1.16.5] Quark - Packet processing error

### ISSUE THREAD

**Issue by GitJhopa** [MinecraftMist/Mist#2]
**Minecraft Version :** 1.16.5

**Mohist Version :** последняя версия

**Operating System :** Windows 10 64 bit

**Logs :** ```[04:04:41 FATAL]: Preparing crash report with UUID 23db1be2-3b28-4d06-9280-0e508656c84b
[04:04:41 ERROR]: Error whilst processing packet net.minecraft.network.play.client.CClickWindowPacket@2487582 for CrackedLix[/95.31.211.125:63913]
net.minecraft.crash.ReportedException: Container click
        at net.minecraft.inventory.container.Container.func_184996_a(Container.java:237) ~[?:?]
        at vazkii.quark.addons.oddities.container.BackpackContainer.func_184996_a(BackpackContainer.java:198) ~[quark:r2.4-314]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:2379) ~[?:?]
        at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?]
        at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:882) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:876) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:135) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:862) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:782) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.inventory.container.WorkbenchContainer.func_217066_a(WorkbenchContainer.java:82) ~[?:?]
        at vazkii.quark.addons.oddities.container.BackpackContainer.func_75130_a(BackpackContainer.java:59) ~[quark:r2.4-314]
        at net.minecraft.inventory.CraftingInventory.func_70299_a(CraftingInventory.java:124) ~[?:?]
        at net.minecraft.inventory.container.Slot.func_75215_d(Slot.java:61) ~[?:?]
        at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:341) ~[?:?]
        at net.minecraft.inventory.container.Container.func_184996_a(Container.java:223) ~[?:?]
        ... 18 more
[04:04:41 INFO]: CrackedLix lost connection: Packet processing error```

**Mod list :** Quark, Quark Oddition

**Plugin list :** дефолтные

**Description of issue :** Когда одеваешь рюкзак из Quark и начинаешь крафтить в инвентаре - вылетает с сервера и в консоли пишет данный краш.

**Comment by Romaindu35** [comment]
You have this error with mist ?

**Comment by GitJhopa** [comment]
> You have this error with mist ?

yes. Mohist too have problem..

**Comment by GitJhopa** [comment]
> You have this error with mist ?

https://youtu.be/dheGr-gIitw

**Comment by Romaindu35** [comment]
> > You have this error with mist ?
> 
> yes. Mohist too have problem..

Yes, but bad commit has been revert in mist, so this error is normally fix too
